name: Setup Python and uv with cache
description: Set up Python, restore/cache uv and venv, and install dependencies

inputs:
  python-version:
    description: Python version to use
    required: true
  dev:
    description: Install dev dependencies (uv sync --dev)
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          .venv
          .ruff_cache
          .mypy_cache
          .pytest_cache
          ~/.cache/uv
        key: ${{ runner.os }}-py${{ inputs.python-version }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-py${{ inputs.python-version }}-uv-

    - name: Install uv
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv

    - name: Install dependencies via uv
      shell: bash
      run: |
        if [[ "${{ inputs.dev }}" == "true" ]]; then
          uv sync --dev
        else
          uv sync
        fi
