name: test-and-deploy

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to build from (e.g., v0.1.0)'
        required: true
        type: string
      repository:
        description: 'Publish target index (pypi or testpypi)'
        required: false
        default: 'pypi'
        type: choice
        options:
          - pypi
          - testpypi

permissions:
  contents: read

env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.pip-cache
  PYTHONPATH: ${{ github.workspace }}/src

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python + uv + cache
        uses: ./.github/actions/setup-uv
        with:
          python-version: '3.10'

      - name: Run Ruff
        run: |
          source .venv/bin/activate
          ruff check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python + uv + cache
        uses: ./.github/actions/setup-uv
        with:
          python-version: '3.10'

      - name: Run MyPy
        run: |
          source .venv/bin/activate
          mypy src

  tests:
    runs-on: ubuntu-latest
    environment: "tests"
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python + uv + cache
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          pytest -m "not int" \
                 --cov=src/fusionbrain_sdk_python \
                 --cov-report=term:skip-covered \
                 --cov-report=xml \
                 -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: pytest
          name: codecov-coverage
          fail_ci_if_error: false
          verbose: true

  integration-tests:
    runs-on: ubuntu-latest
    environment: "tests"
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.10' ]
    env:
      FB_API_KEY: ${{ secrets.FB_API_KEY }}
      FB_API_SECRET: ${{ secrets.FB_API_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python + uv + cache
        uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run integration tests
        run: |
          source .venv/bin/activate
          pytest -m int -v

  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Verify tag exists and format
        shell: bash
        run: |
          if [[ ! "${{ inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
            echo "Tag must start with v and follow semver, e.g. v1.2.3" >&2
            exit 1
          fi
          git fetch --tags --quiet
          if ! git rev-parse -q --verify "refs/tags/${{ inputs.tag }}" >/dev/null; then
            echo "Tag ${{ inputs.tag }} not found in repository" >&2
            exit 1
          fi

      - name: Setup Python + uv + cache
        uses: ./.github/actions/setup-uv
        with:
          python-version: '3.10'
          dev: 'false'

      - name: Build package (sdist + wheel)
        run: |
          source .venv/bin/activate
          uv build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*
          retention-days: 7

  publish:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist

      - name: Publish to TestPyPI
        if: ${{ inputs.repository == 'testpypi' }}
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          packages-dir: dist
          skip-existing: true

      - name: Publish to PyPI
        if: ${{ inputs.repository == 'pypi' }}
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
          skip-existing: true
